#!/bin/bash
set -e
shopt -s extglob
cd "$(dirname "$0")"

[[ "$(uname -s)" = "Darwin" ]] && is_mac=true

if [[ $# -ne 1 && $# -ne 2 ]]; then 
	if [[ "${is_mac}" = true ]]; then
		echo "Usage: $0 <linux version such as ubuntu18.04> [path to xctoolchain]"
	else
		echo "Usage: $0 <linux version such as ubuntu18.04> <swift version>"
	fi
	exit 1
fi

info() { echo "[info] $1"; }

linux_version="$1"

mkdir -p toolchains

if [[ "${is_mac}" = true ]]; then
	mac_toolchain="$(cd "${2:-"$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain"}" && pwd)"
	swift_version="$("${mac_toolchain}/usr/bin/swift" --version | head -1 | cut -f4 -d" ")"
	info "Detected Swift version ${swift_version}"
	cd toolchains
else
	swift_version="$2"
	file_name_mac="swift-${swift_version}-RELEASE-osx"
	package_mac="${file_name_mac}-package.pkg"
	info "Downloading macOS toolchain"
	cd toolchains
	if [[ ! -f "toolchain-mac-${swift_version}.pkg" ]]; then
		curl -#o "toolchain-mac-${swift_version}.pkg" "https://swift.org/builds/swift-${swift_version}-release/xcode/swift-${swift_version}-RELEASE/${file_name_mac}.pkg"
	fi
	info "Unpacking macOS toolchain"
	rm -rf mac
	xar -xf "toolchain-mac-${swift_version}.pkg" "${package_mac}/Payload"
	cd "${package_mac}"
	mkdir -p out
	cd out
	gzip -cd ../Payload | cpio -i
	cd ..
	mv out ../mac
	cd ..
	rm -rf "${package_mac}"
	mac_toolchain="mac"
fi

file_name_linux="swift-${swift_version}-RELEASE-${linux_version}"

if [[ ! -f "toolchain-${linux_version}-${swift_version}.tar.gz" ]]; then
	info "Downloading Linux toolchain"
	curl -#o "toolchain-${linux_version}-${swift_version}.tar.gz" "https://swift.org/builds/swift-${swift_version}-release/${linux_version/./}/swift-${swift_version}-RELEASE/${file_name_linux}.tar.gz"
fi

info "Unpacking Linux toolchain"
# remove any pre-existing usr dir first
rm -rf usr
tar -xzf "toolchain-${linux_version}-${swift_version}.tar.gz"
mv "${file_name_linux}/usr" .
rm -rf "${file_name_linux}"

info "Modifying Linux toolchain"
mv usr/lib/swift{,_linux}
cp -a "${mac_toolchain}"/usr/lib/{swift,arc} usr/lib/
rm usr/lib/swift/clang
mv usr/lib/swift_linux/clang usr/lib/swift/

info "Packaging toolchain"
mkdir -p ../packages
mv usr swift
tar -czf "../packages/swift-${swift_version}-${linux_version}.tar.gz" swift
rm -rf swift mac
