#!/bin/bash
set -e
shopt -s extglob
cd "$(dirname "$0")"

if [[ $# -ne 4 ]]; then 
	echo "Usage: $0 <major> <minor> <patch> <linux version such as ubuntu16.10>"
	exit 1
fi

info() { echo "[info] $1"; }

version="$1.$2.$3"
file_name_mac="swift-${version}-RELEASE-osx"
file_name_linux="swift-${version}-RELEASE-$4"
package="${file_name_mac}-package.pkg"

mkdir -p toolchains
cd toolchains

info "Downloading macOS toolchain"
if [[ ! -f "toolchain-mac-${version}.pkg" ]]; then
	curl -#o "toolchain-mac-${version}.pkg" "https://swift.org/builds/swift-${version}-release/xcode/swift-${version}-RELEASE/${file_name_mac}.pkg"
fi

info "Unpacking macOS toolchain"
rm -rf mac
xar -xf "toolchain-mac-${version}.pkg" "${package}/Payload"
tar -xzf "${package}/Payload" usr
mv usr mac
rm -rf "${package}"

info "Downloading Linux toolchain"
if [[ ! -f "toolchain-$4-${version}.tar.gz" ]]; then
	curl -#o "toolchain-$4-${version}.tar.gz" "https://swift.org/builds/swift-${version}-release/${4/./}/swift-${version}-RELEASE/${file_name_linux}.tar.gz"
fi

info "Unpacking Linux toolchain"
# remove any pre-existing usr dir first
rm -rf linux
tar -xzf "toolchain-$4-${version}.tar.gz"
mv "${file_name_linux}/usr" .
rm -rf "${file_name_linux}"

info "Modifying Linux toolchain"
rm -rf usr/lib/swift/!(clang|migrator|shims) usr/lib/swift_static/*
cp -a mac/lib/swift/iphoneos usr/lib/swift/
cp -a mac/lib/swift_static/iphoneos usr/lib/swift_static/
rm -rf mac

info "Packaging toolchain"
mv usr swift
tar -czf "../swift-${version}-$4.tar.gz" swift
rm -rf swift
