name: Create Release

on:
  - push
  - workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu22.04, ubuntu20.04, ubuntu18.04]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@main
    - name: Build Release
      id: build_release
      run: |
        ./create-toolchain ${{ matrix.os }}

    - uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.os }}-toolchain
        path: packages/*-${{ matrix.os }}.tar.xz

  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@main
    - name: Download Artifacts
      uses: actions/download-artifact@main

    - name: Set TAG Variable
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG }}
        release_name: Draft Release
        body: ''
        draft: true

    - name: Attach Builds To Release
      run: |
        set -x
        toolchains=()
        for tc in **/*.tar.xz; do
          toolchains+=("-a" "$tc")
        done
        hub release edit "${toolchains[@]}" -m "Draft Release" "$TAG"
