name: Create Release

on:
  - push
  - workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Draft Release
        body: ''
        draft: true

  build:
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu22.04-aarch64, ubuntu22.04, ubuntu20.04-aarch64, ubuntu20.04, ubuntu18.04]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@main
    - name: Build Release
      id: build_release
      run: |
        ./create-toolchain ${{ matrix.os }}

    - name: Attach Build To Release
      run: |
        set -x
        gh release upload ${GITHUB_REF##*/} packages/*-${{ matrix.os }}.tar.xz
