name: Create Release

on:
  - push
  - workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Release
      id: create_release
      run: |
        release_tag="$(uuidgen)"
        echo "release_tag=${release_tag}" >> "${GITHUB_OUTPUT}"
        gh release create "${release_tag}" --draft --target "${GITHUB_SHA}"

  build:
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu22.04-aarch64, ubuntu22.04, ubuntu20.04-aarch64, ubuntu20.04, ubuntu18.04]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Release
      id: build_release
      run: |
        ./create-toolchain ${{ matrix.os }}

    - name: Attach Build To Release
      run: |
        set -x
        gh release upload ${{ steps.create_release.outputs.release_tag }} packages/*-${{ matrix.os }}.tar.xz
